# Generated by Django 3.1.4 on 2021-01-31 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(default=1, upload_to='images', verbose_name='Foto de perfil'),
            preserve_default=False,
        ),
    ]
