# Generated by Django 3.1.3 on 2021-01-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocioEconomicStudy',
            fields=[
                ('study_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre(s)')),
                ('primer_apellido', models.CharField(max_length=15, verbose_name='Apellido paterno')),
                ('segundo_apellido', models.CharField(max_length=15, verbose_name='Apellido materno')),
                ('poverty_range', models.CharField(choices=[('0', 'Muy bajo'), ('1', 'Bajo'), ('2', 'Medio'), ('3', 'Alto'), ('4', 'Muy alto')], max_length=100, verbose_name='Rango  de pobreza en donde se ubica su colonia')),
                ('general_average', models.CharField(choices=[('0', 'De 8.5 a 9.0'), ('1', 'De 9.1 a 10')], max_length=100, verbose_name='Promedio General')),
                ('family_integrants', models.CharField(choices=[('0', 'De 1 a 3'), ('1', 'De 4 a 7'), ('2', 'Más de 7')], max_length=100, verbose_name='Número de integrantes de la familia')),
                ('section1_obs', models.CharField(max_length=100, null=True, verbose_name='Observaciones')),
                ('punct_section1', models.IntegerField(verbose_name='puntuación total obtenida en el apartado ')),
                ('dad_occupation', models.CharField(max_length=30, null=True, verbose_name='Ocupación del padre ')),
                ('dad_income', models.FloatField(verbose_name='Ingresos mensuales del padre ')),
                ('mom_occupation', models.CharField(max_length=30, null=True, verbose_name='Ocupación de la madre ')),
                ('mom_income', models.FloatField(verbose_name='Ingresos mensuales de la madre ')),
                ('son_occupation', models.CharField(max_length=30, null=True, verbose_name='Ocupación del hijo ')),
                ('son_income', models.FloatField(verbose_name='Ingresos mensuales del hijo ')),
                ('candidate_occupation', models.CharField(max_length=30, null=True, verbose_name='Ocupación del candidato ')),
                ('candidate_income', models.FloatField(verbose_name='Ingresos mensuales del candidato ')),
                ('candidate_workplace', models.CharField(max_length=15, null=True, verbose_name='Lugar de trabajo del candidato')),
                ('family_income', models.CharField(choices=[('0', 'De $0 a $3,696 pesos'), ('1', 'Más de $3,696 y hasta $7,393 pesos'), ('2', 'Más de $7,393 y hasta $11,089 pesos'), ('3', 'Más de $11,089 y hasta $14,786 pesos'), ('4', 'Más de $14,786 y hasta $18,483 pesos'), ('4', 'Más de $18,483 pesos')], max_length=50, verbose_name='Ingreso total familiar mensual')),
                ('exp_food', models.FloatField(verbose_name='Gastos mensuales aproximados en comida ')),
                ('exp_rent', models.FloatField(verbose_name='Gastos mensuales aproximados en renta/hipoteca ')),
                ('exp_water', models.FloatField(verbose_name='Gastos mensuales aproximados en  el  servicio de agua')),
                ('exp_elect', models.FloatField(verbose_name='Gastos mensuales aproximados en el servicio de electricidad')),
                ('exp_diversion', models.FloatField(verbose_name='Gastos mensuales aproximados dedicados a la diversión ')),
                ('exp_transport', models.FloatField(verbose_name='Gastos mensuales aproximados dedicados al transporte')),
                ('exp_education', models.FloatField(verbose_name='Gastos mensuales aproximados dedicados a la educación')),
                ('exp_tv_internet', models.FloatField(verbose_name='Gastos mensuales aproximados dedicados a servicios de cable Tv e internet')),
                ('exp_otros', models.FloatField(verbose_name='Otros gastos ')),
                ('section2_obs', models.CharField(max_length=100, null=True, verbose_name='Observaciones')),
                ('punct_section2', models.IntegerField(verbose_name='puntuación total obtenida en el apartado ')),
                ('dad_scholar', models.CharField(choices=[('0', 'Ninguna'), ('1', 'Primaria'), ('2', 'Secundaria'), ('3', 'Preparatoria/Carrera técnica'), ('4', 'Licenciatura'), ('5', 'Maestría/Doctorado')], max_length=100, verbose_name='Escolaridad del padre o tutor')),
                ('mom_scholar', models.CharField(choices=[('0', 'Ninguna'), ('1', 'Primaria'), ('2', 'Secundaria'), ('3', 'Preparatoria/Carrera técnica'), ('4', 'Licenciatura'), ('5', 'Maestría/Doctorado')], max_length=100, verbose_name='Escolaridad de la madre')),
                ('cand_scholar', models.CharField(choices=[('0', 'Ninguna'), ('1', 'Primaria'), ('2', 'Secundaria'), ('3', 'Preparatoria/Carrera técnica'), ('4', 'Licenciatura'), ('5', 'Maestría/Doctorado')], max_length=100, verbose_name='Escolaridad del candidato')),
                ('spous_scholar', models.CharField(choices=[('0', 'Ninguna'), ('1', 'Primaria'), ('2', 'Secundaria'), ('3', 'Preparatoria/Carrera técnica'), ('4', 'Licenciatura'), ('5', 'Maestría/Doctorado')], max_length=100, verbose_name='Escolaridad del esposo/a')),
                ('section3_obs', models.CharField(max_length=100, null=True, verbose_name='Observaciones')),
                ('punct_section3', models.IntegerField(verbose_name='puntuación total obtenida en el apartado ')),
                ('healt_prov', models.CharField(choices=[('0', 'Ninguno'), ('1', 'Médico particular'), ('2', 'IMSS-ISSSTE-PEMEX-INSABI-Gastos médicos')], max_length=100, verbose_name='El principal proveedor en el hogar está registrado o afiliado en:')),
                ('employment_benefits', models.CharField(choices=[('0', 'Ninguna prestación'), ('1', 'Servicio médico, sistema de ahorro para retiro, incapacidad laboral con goce de sueldo')], max_length=100, verbose_name='Principal proveedor en el hogar económicamente activo, asalariado con todas y cada una de las siguientes prestaciones laborales:')),
                ('section4_obs', models.CharField(max_length=100, null=True, verbose_name='Observaciones')),
                ('punct_section4', models.IntegerField(verbose_name='puntuación total obtenida en el apartado ')),
                ('home_type', models.CharField(choices=[('0', 'Prestada'), ('1', 'Rentada'), ('2', 'La están pagando'), ('3', 'Propia')], max_length=100, verbose_name='La casa que habita la familia es:')),
                ('floor_type', models.CharField(choices=[('0', 'Firme de cemento, tierra'), ('1', 'Con recubrimiento (laminado, vitropiso, mosaico, madera)')], max_length=100, verbose_name='el piso  de su vivienda es:')),
                ('ceiling_type', models.CharField(choices=[('0', 'Prestada'), ('1', 'Rentada'), ('2', 'La están pagando'), ('3', 'Propia')], max_length=100, verbose_name='El techo de su vivienda es:')),
                ('walls_tipe', models.CharField(choices=[('0', 'Adobe'), ('1', 'Piedra'), ('2', 'Madera'), ('3', 'Block'), ('4', 'Tabique o ladrillo')], max_length=100, verbose_name='Los muros de su vivienda son de:')),
                ('room_persons', models.CharField(choices=[('0', 'Número  de personas por cuarto mayor a 2.5'), ('1', 'Número  de personas por cuarto menor a 2.5')], max_length=100, verbose_name='Número de personas por cuarto:')),
                ('water_service', models.CharField(choices=[('0', 'Si'), ('1', 'No')], max_length=100, verbose_name='¿ Su casa cuenta con servicio de agua entubada dentro de la vivienda o fuera de la vivienda, pero dentro del terreno ?:')),
                ('drain_service', models.CharField(choices=[('0', 'Si'), ('1', 'No')], max_length=100, verbose_name='¿ Su casa cuenta con servicio de drenaje conectado a una red pública o a una fora séptica ?:')),
                ('elect_service', models.CharField(choices=[('0', 'Si'), ('1', 'No')], max_length=100, verbose_name='¿ Su casa cuenta con servicio de electricidad obtenido del servicio público, de panel solar o de otra fuente, planta paticular?:')),
                ('fuel_service', models.CharField(choices=[('0', 'Si'), ('1', 'No')], max_length=100, verbose_name='¿ Su casa cuenta con servicio de drenaje conectado a una red pública o a una fora séptica ?:')),
                ('section5_obs', models.CharField(max_length=100, null=True, verbose_name='Observaciones')),
                ('punct_section5', models.IntegerField(verbose_name='puntuación total obtenida en el apartado ')),
                ('veracity', models.BooleanField(blank=True, null=True, verbose_name=' ¿ Confirma que toda la informacion proporcionada es verídica ?')),
                ('total_punct', models.IntegerField(verbose_name='puntuación total obtenida en  el ESE ')),
                ('porcent_punct', models.IntegerField(verbose_name='nivel de vulnerabilidad o pobreza obtenido  en  el Estudio Socio Económico (Porciento) ')),
                ('poverty_level', models.IntegerField(verbose_name='nivel de vulnerabilidad o pobreza obtenido  en  el Estudio Socio Económico (Puntos)')),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
