# Generated by Django 3.1.4 on 2021-01-25 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "becas",
            "0002_averagegraderanges_familymembersrange_familymonthlyincome_homeceil_homefloor_homepersons_hometype_ho",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socioeconomicstudy",
            name="ceiling_type",
        ),
        migrations.RemoveField(
            model_name="socioeconomicstudy",
            name="drain_service",
        ),
        migrations.RemoveField(
            model_name="socioeconomicstudy",
            name="elect_service",
        ),
        migrations.RemoveField(
            model_name="socioeconomicstudy",
            name="employment_benefits",
        ),
        migrations.RemoveField(
            model_name="socioeconomicstudy",
            name="floor_type",
        ),
        migrations.RemoveField(
            model_name="socioeconomicstudy",
            name="fuel_service",
        ),
        migrations.RemoveField(
            model_name="socioeconomicstudy",
            name="porcent_punct",
        ),
        migrations.RemoveField(
            model_name="socioeconomicstudy",
            name="poverty_level",
        ),
        migrations.RemoveField(
            model_name="socioeconomicstudy",
            name="punct_section4",
        ),
        migrations.RemoveField(
            model_name="socioeconomicstudy",
            name="room_persons",
        ),
        migrations.RemoveField(
            model_name="socioeconomicstudy",
            name="section4_obs",
        ),
        migrations.RemoveField(
            model_name="socioeconomicstudy",
            name="total_punct",
        ),
        migrations.RemoveField(
            model_name="socioeconomicstudy",
            name="veracity",
        ),
        migrations.RemoveField(
            model_name="socioeconomicstudy",
            name="walls_tipe",
        ),
        migrations.RemoveField(
            model_name="socioeconomicstudy",
            name="water_service",
        ),
        migrations.AlterField(
            model_name="socioeconomicstudy",
            name="home_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="becas.hometype",
                verbose_name="Tipo de vivienda",
            ),
        ),
        migrations.AlterField(
            model_name="studentacademicprogram",
            name="promedio",
            field=models.FloatField(verbose_name="Promedio general"),
        ),
    ]
