# Generated by Django 3.1.4 on 2021-01-28 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("becas", "0003_auto_20210125_0239"),
        ("becas", "0002_socioeconomicstudy"),
    ]

    operations = []
