# Generated by Django 3.1.4 on 2021-02-01 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('becas', '0003_auto_20210131_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagegraderanges',
            name='average_grade_range',
            field=models.CharField(max_length=50, verbose_name='Promedio general'),
        ),
        migrations.AlterField(
            model_name='estados',
            name='estado',
            field=models.CharField(max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='grados',
            name='grado',
            field=models.CharField(max_length=50, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='modalidades',
            name='modalidad',
            field=models.CharField(max_length=50, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='municipio',
            field=models.CharField(max_length=50, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='povertyrange',
            name='poverty',
            field=models.CharField(max_length=50, verbose_name='Rango de pobreza de su colonia'),
        ),
        migrations.AlterField(
            model_name='socioeconomicstudy',
            name='candidate_occupation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='socioeconomicstudy',
            name='dad_occupation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='socioeconomicstudy',
            name='mom_occupation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='socioeconomicstudy',
            name='other_occupation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='socioeconomicstudy',
            name='son_occupation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='socioeconomicstudy',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='nombre',
            field=models.CharField(max_length=35, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=25, verbose_name='Número de identifcación del estudiante'),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentacademicprogram',
            name='continua',
            field=models.BooleanField(max_length=50, verbose_name='En caso de TSU, planeo continuar con mis estudios a nivel licenciatura o ingeniería.'),
        ),
        migrations.AlterField(
            model_name='studentacademicprogram',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='universities',
            name='university',
            field=models.CharField(max_length=50, verbose_name='Universidad'),
        ),
    ]
