# Generated by Django 3.1.4 on 2021-02-04 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("becas", "0002_auto_20210204_0724"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enlaces",
            fields=[
                (
                    "username",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="auth.user",
                    ),
                ),
                ("nombre", models.CharField(max_length=25, verbose_name="Nombre(s)")),
                (
                    "primer_apellido",
                    models.CharField(max_length=15, verbose_name="Apellido paterno"),
                ),
                (
                    "segundo_apellido",
                    models.CharField(max_length=15, verbose_name="Apellido materno"),
                ),
                (
                    "university",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="becas.universities",
                        verbose_name="Universidad",
                    ),
                ),
            ],
        ),
    ]
