# Generated by Django 3.1.3 on 2020-12-29 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Modalidades",
            fields=[
                ("modalidad_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "modalidad",
                    models.CharField(max_length=30, verbose_name="Modalidad"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Convocatorias",
            fields=[
                (
                    "convocatoria_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("codigo", models.CharField(max_length=8, verbose_name="Código")),
                ("name", models.CharField(max_length=30, verbose_name="Nombre")),
                (
                    "description",
                    models.CharField(max_length=256, verbose_name="Descripción"),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de apertura")),
                ("end_date", models.DateField(verbose_name="Fecha de cierre")),
                (
                    "results_date",
                    models.DateField(verbose_name="Publicación de resultados"),
                ),
                (
                    "presupuesto",
                    models.IntegerField(verbose_name="Presupuesto asignado"),
                ),
                (
                    "modalidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="convocatoria.modalidades",
                        verbose_name="Modalidad",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aspirantes",
            fields=[
                ("folio", models.AutoField(primary_key=True, serialize=False)),
                ("grade", models.IntegerField(null=True, verbose_name="Calificación")),
                (
                    "socioeconomic_score",
                    models.IntegerField(
                        null=True, verbose_name="Estudio socioeconómico"
                    ),
                ),
                (
                    "grneral_score",
                    models.IntegerField(
                        null=True, verbose_name="Estudio socioeconómico"
                    ),
                ),
                (
                    "beneficiado",
                    models.BooleanField(null=True, verbose_name="Beneficiado"),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "convocatoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="convocatoria.convocatorias",
                        verbose_name="Convocatoria",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
