# Generated by Django 3.1.4 on 2021-02-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("convocatoria", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aspirantes",
            name="general_score",
        ),
        migrations.AddField(
            model_name="aspirantes",
            name="comments",
            field=models.TextField(null=True, verbose_name="Comentarios"),
        ),
    ]
