# Generated by Django 3.1.4 on 2021-01-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspirantes',
            name='grneral_score',
        ),
        migrations.AddField(
            model_name='aspirantes',
            name='general_score',
            field=models.IntegerField(null=True, verbose_name='Score'),
        ),
    ]
