# Generated by Django 3.1.4 on 2021-01-28 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0002_auto_20210125_0034'),
        ('convocatoria', '0002_auto_20210114_0052'),
    ]

    operations = [
    ]
